### PR TITLE
GitHub workflows + Buildbuddy

### PR DESCRIPTION
**Pull request by or-shachar**
1. Removed cirrus CI
2. Added Buildbuddy configuration (Resultstore + remote cache)
3. Added github workflows matrix configuration to test with IJ 2020.1 and 2020.2

### CODE REVIEW

**Comment by ZachiNachshon** [comment]
This contribution is highly appreciated @or-shachar !
Since upstream doesn't officially support `2020.2.x` think that we shouldn't add it to our CI cycle.

**Comment by or-shachar** [comment]
Changed it to experimental and I'll remove the intellij-beta given that it's an alias to 2020.1

**Comment by or-shachar** [comment]
Ok... so I guess my work is done.
Thanks to @sha1n for helping me to add `--remote_timeout=5 and --remote_retries=0` which saves the time on uploading / download large files from remote cache.

Regarding intellij `2020.2` - I think Github actions is a little buggy with [continue-on-error](https://docs.github.com/en/free-pro-team@latest/actions/reference/workflow-syntax-for-github-actions#jobsjob_idcontinue-on-error) feature. If I configure it to the whole job, it just doesn't work (the workflow is marked as failed). If I configure it per step it hides the failure completely. (I'd expect some orange/ gray feedback of "failed, but continuing").  If you wish - you can just drop the 2020.2 for now

@ZachiNachshon  - you can take it from here :)

**Comment by ZachiNachshon** [comment]
Amazing work, thanks for super charging this repo CI flow 🚀 
I'll remove `2020.2` for now since it contains tests failure but marked as success in GitHub actions as you've specified.

**Review by ZachiNachshon — APPROVED** [review]
LGTM !

**Pull request merged**
