### PR TITLE
Change autoscrollToConsole default to true

### PR DESCRIPTION
**Pull request by koiuo**
Addresses https://github.com/wix-private/wix-intellij-plugin/pull/277

This is until the change is accepted upstream https://github.com/bazelbuild/intellij/issues/3106

### CODE REVIEW

**Comment by koiuo** [comment]
Disclaimer, I created this patch through github UI and have not checked it actually works, nor run any tests

**Comment by ittaiz** [comment]
@edio can you check that it actually works? do we have a boolean for "double click"?
I really want to see this getting in

**Comment by koiuo** [comment]
@ittaiz , I verified and can confirm, that with this patch the autoscroll button is enabled on a new projects imported into intellij

**Comment by ittaiz** [comment]
Thanks! @liucijus can we merge?

**Comment by ittaiz** [comment]
Yay! Thanks 🥳

**Pull request merged**
