### PR TITLE
Same repo import issue resolver

### PR DESCRIPTION
**Pull request by or-shachar**

### CODE REVIEW

**Comment by or-shachar** [comment]
@hmemcpy  - pls review. I'm merging...

**Comment by hmemcpy** [comment]
Looking...

**Comment by hmemcpy** [comment]
My only comment is squishing some commits into distinct descriptions, leaving maybe 2: the squiggly and the quickfix.
Also, I'm not 100% sure how they like Java's `Optional`s. They're quite awkward, I think they mostly use nulls everywhere instead.

**Comment by hmemcpy** [comment]
@idankWix is there anything specific you want me to look at?

**Pull request merged**
